#index:
#    path: /
#    controller: App\Controller\DefaultController::index
dons_page:
    path: /dons/{userId}
    controller: App\Controller\DonsController::index
# config/routes.yaml
don_delete:
    path: /dons/{id}/delete
    controller: App\Controller\DonsController::delete
    methods: [POST] # Vous pouvez également inclure DELETE si vous voulez supporter les deux méthodes

# config/routes.yaml

edit_don:
    path: '/edit/{id}'
    controller: 'App\Controller\DonsController::editDon'

demander_dons:
    path: '/demander_dons/{idUser}'
    controller: 'App\Controller\DemandeDonsController::demanderDons'
    methods: ['GET', 'POST']



transfer_points:
    path: /transfer_points/{idUser}
    controller: 'App\Controller\DemandeDonsController::transferPoints'
    methods: ['POST']

admin_dons:
    path: /admin/dons
    controller: App\Controller\DonsController::backDons


update_etat_dons:
    path: '/update_etat_dons/{id}'
    controller: 'App\Controller\DonsController::updateEtatDons'
    methods: ['POST']

admin_demandedons:
    path: '/admin/demandedons'
    controller: 'App\Controller\DemandeDonsController::backDemandesDons'


add_points_to_event_form:
    path: '/evenement/{eventId}/ajouter-points'
    controller: 'App\Controller\DonsController::addPointsToEventForm'
    methods: ['GET', 'POST']



admin_dons_delete:
    path: /admin/dons/{id}/delete
    controller: App\Controller\DonsController::deleteDon
    methods: ['GET', 'POST']

admin_demandedons_delete:
    path: /admin/demandedons/{id}/delete
    controller: App\Controller\DemandeDonsController::deleteDemande
    methods: ['GET', 'POST']

modifier_points_don:
    path: '/modifier-points/{id}'
    controller: 'App\Controller\DonsController::modifierPointsDon'
    methods: ['GET', 'POST']


modifier_points_demande_don:
    path: /modifier-points-demande/{id}
    controller: App\Controller\DemandeDonsController::modifierPointsDemandeDon
    methods: ['GET', 'POST']


demander_dons_action:
    path: /demander_dons_action
    controller: App\Controller\DemandeDonsController::demanderDonsAction
    methods: [GET, POST]

generate_qr_code:
    path: '/generate-qr-code/{content}'
    controller: 'App\Controller\QrCodeGeneratorController::generateQrCodeUri'

afficher_dons:
    path: /afficher-dons
    controller: App\Controller\DonsController::afficherDonsFiltre



